services:
  dnd-monsters:
    build: .
    ports:
      - "80:80"

    environment:
        - environment=local
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--timeout", "75", "--log-level", "info"]


    